import 'emotion_interpreter.dart';
import 'crisis_detector.dart';
import 'ai_provider.dart';

class EmotionalResponse {
  const EmotionalResponse({
    required this.greeting,
    required this.validation,
    required this.interpretation,
    required this.suggestion,
    required this.reflectionQuestion,
    required this.emergencyRisk,
    this.aiMessage,
  });

  final String greeting;
  final String validation;
  final String interpretation;
  final String suggestion;
  final String reflectionQuestion;
  final bool emergencyRisk;
  final String? aiMessage;

  bool get hasAIMessage => aiMessage != null && aiMessage!.isNotEmpty;
}

class _MessageBank {
  const _MessageBank({
    required this.greetings,
    required this.validations,
    required this.interpretations,
    required this.suggestions,
    required this.questions,
  });

  final List<String> greetings;
  final List<String> validations;
  final List<String> interpretations;
  final List<String> suggestions;
  final List<String> questions;
}

class EmotionalResponseEngine {
  const EmotionalResponseEngine._();

  static final Map<String, _MessageBank> _banks = {
    'tristeza': _MessageBank(
      greetings: [
        'Veo que hoy no es un día fácil para ti.',
        'Gracias por confiarme lo que sientes.',
        'Me alegra que hayas podido escribir esto.',
        'Lamento que estés pasando por esto.',
        'No es fácil poner en palabras lo que uno siente.',
        'Qué bueno que estés aquí.',
        'Tu diario es un buen lugar para soltar.',
        'Estoy aquí para leerte.',
        'Gracias por abrirte.',
        'Me alegra que estés expresando lo que sientes.',
        'Siento que estés pasando por un momento difícil.',
        'Tu corazón tiene cosas que decir.',
        'Hoy parece ser un día pesado.',
        'Es valiente escribir cuando todo se siente gris.',
        'Me importa lo que sientes.',
      ],
      validations: [
        'Sentir tristeza es completamente válido.',
        'No tienes que sonar fuerte todo el tiempo.',
        'Está bien no estar bien.',
        'Tu tristeza tiene derecho a existir.',
        'No estás exagerando por sentirte así.',
        'Lo que sientes es real y merece ser escuchado.',
        'No hay forma "correcta" de sentirse triste.',
        'Es humano llorar, incluso en silencio.',
        'No tienes que minimizar lo que sientes.',
        'Tu dolor no es menor por no tener explicación.',
        'No necesitas justificar por qué estás triste.',
        'Darte permiso para sentir es el primer paso.',
        'No estás solo en esto, aunque se sienta así.',
        'Tu tristeza no es un defecto.',
        'Está bien tomarse un momento para sentir.',
      ],
      interpretations: [
        'Parece que algo te está doliendo por dentro.',
        'Da la impresión de que hay una carga emocional pesada.',
        'Puede ser que estés procesando una pérdida o decepción.',
        'Se percibe una sensación de pesadez emocional.',
        'Es posible que algo haya desencadenado estos sentimientos.',
        'Parece que hay algo que te está afectando profundamente.',
        'Da la impresión de que el corazón está pidiendo atención.',
        'Se nota que algo te está pesando en el alma.',
        'Puede ser que estés atravesando un momento de duelo.',
        'Parece que necesitas un espacio para sanar.',
      ],
      suggestions: [
        'Tal vez un momento de silencio te ayude a ordenar.',
        '¿Qué tal si sales a caminar un poco?',
        'Escribir puede ayudarte a entender qué sientes.',
        'Respirar profundo tres veces puede darte un respiro.',
        'Escuchar algo tranquilo puede ayudarte a relajarte.',
        'Tomar algo caliente puede darte un momento de calma.',
        'A veces un abrazo largo puede ayudar.',
        '¿Qué tal si pones música que te guste?',
        'Un baño caliente puede ayudar a soltar la tensión.',
        'Dormir un rato puede darte perspectiva.',
        'Hablar con alguien de confianza puede aliviar.',
        'Escribir sin filtro puede liberar lo que cargas.',
      ],
      questions: [
        '¿Qué crees que desencadenó esto?',
        '¿Desde cuándo te sientes así?',
        '¿Qué sería lo que más necesitas hoy?',
        '¿Hay algo que pueda hacer que se sienta un poco mejor?',
        '¿Qué fue lo último que te hizo sentir bien?',
        '¿Necesitas hablar o simplemente ser escuchado?',
        '¿Qué sería diferente si pudieras cambiar algo?',
        '¿Hay algo que estés evitando enfrentar?',
        '¿Qué te gustaría que alguien te dijera ahora?',
        '¿Cuándo fue la última vez que te sentiste en paz?',
      ],
    ),
    'ansiedad': _MessageBank(
      greetings: [
        'Veo que tu mente está muy activa hoy.',
        'Parece que hay mucha preocupación en lo que escribes.',
        'Gracias por compartir lo que te preocupa.',
        'Tu ansiedad se siente en cada palabra.',
        'Entiendo que esto te está generando inquietud.',
        'No es fácil llevar ese peso en la mente.',
        'Parece que la incertidumbre te está afectando.',
        'Estoy aquí para leerte sin juzgarte.',
        'Me alegra que estés expresando lo que te agobia.',
        'Tu mente está trabajando demasiado rápido.',
        'Se nota que hay mucho en tu cabeza.',
        'Gracias por tomarte el tiempo de escribir.',
      ],
      validations: [
        'La ansiedad no es debilidad, es una respuesta natural.',
        'No estás loco por sentirte así.',
        'Tu preocupación es comprensible dada la situación.',
        'Es válido sentirse abrumado a veces.',
        'No tienes que tener todo bajo control.',
        'Sentir ansiedad no significa que algo esté mal contigo.',
        'Tu mente intenta protegerte, aunque a veces se pase.',
        'No es fácil vivir con tanta incertidumbre.',
        'Tu ansiedad merece ser tomada en serio.',
        'No estás exagerando, la sensación es real.',
        'Está bien admitir que no puedes con todo.',
        'Tu cerebro está en modo alerta, es comprensible.',
        'No necesitas resolver todo de inmediato.',
        'Permítete sentir sin criticarte.',
      ],
      interpretations: [
        'Parece que la incertidumbre te está generando tensión.',
        'Da la impresión de que tu mente está anticipando problemas.',
        'Puede ser que estés preocupado por algo que aún no ha pasado.',
        'Se percibe una sensación de estar en alerta constante.',
        'Es posible que tu cuerpo esté respondiendo al estrés acumulado.',
        'Parece que hay una preocupación que no te deja en paz.',
        'Da la impresión de que necesitas un momento de calma.',
        'Se nota que la mente no para de dar vueltas.',
        'Puede ser que estés anticipando peor escenarios.',
        'Parece que la presión te está consumiendo.',
      ],
      suggestions: [
        'Respirar lento: inhalar 4 segundos, sostener 4, exhalar 4.',
        '¿Qué tal si pones los pies en el suelo y sientes la tierra?',
        'Escribir todas tus preocupaciones puede sacarlas de tu cabeza.',
        'Una caminata corta puede ayudar a bajar la intensidad.',
        '¿Qué tal si te enfocas en solo esta hora?',
        'Beber agua despacio puede calmar tu sistema.',
        'Pon una mano en tu pecho y siente tu corazón.',
        '¿Qué tal si haces una pausa de 5 minutos?',
        'Escuchar sonidos de la naturaleza puede relajarte.',
        'Estirar el cuerpo puede liberar la tensión acumulada.',
        'A veces solo necesitas que alguien te diga que todo estará bien.',
      ],
      questions: [
        '¿Qué es lo que más te está preocupando?',
        '¿Desde cuándo sientes esta inquietud?',
        '¿Hay algo que puedas controlar en esta situación?',
        '¿Qué sería lo peor que podría pasar?',
        '¿Qué le dirías a un amigo que se sintiera así?',
        '¿Necesitas hacer una pausa ahora mismo?',
        '¿Qué te ayuda a calmarte cuando estás así?',
        '¿Hay algo que estés postergando por miedo?',
        '¿Qué cambiaría si pudieras soltar un poco?',
        '¿Cuándo fue la última vez que te sentiste tranquilo?',
      ],
    ),
    'estres': _MessageBank(
      greetings: [
        'Parece que hoy estás cargando mucho.',
        'Veo que las cosas no están fáciles.',
        'Gracias por tomarte este momento para escribir.',
        'Se nota que la presión se ha sentido fuerte.',
        'No es fácil llevar tanto peso encima.',
        'Tu esfuerzo se nota en cada palabra.',
        'Estoy aquí para leerte.',
        'Me importa lo que estás viviendo.',
        'Tu diario es un buen lugar para descargar.',
        'Hoy parece haber sido agotador.',
        'Parece que has estado dando mucho de ti.',
        'Gracias por confiarme cómo te sientes.',
      ],
      validations: [
        'No es fácil mantenerlo todo junto.',
        'Tu esfuerzo es real, aunque no se reconozca.',
        'Está bien decir "no puedo más" a veces.',
        'No tienes que ser perfecto para ser suficiente.',
        'Tu cansancio es válido.',
        'No es debilidad necesitar un descanso.',
        'Llevar presión constante agota a cualquiera.',
        'Tu cuerpo te está pidiendo una pausa.',
        'No tienes que resolver todo hoy.',
        'Está bien pedir ayuda cuando se necesita.',
        'Tu límite es real, no lo ignores.',
        'No estás fallando, estás sobreviviendo.',
      ],
      interpretations: [
        'Parece que estás en un estado de presión acumulada.',
        'Da la impresión de que las exigencias te están superando.',
        'Puede ser que necesites priorizar y soltar algo.',
        'Se percibe un agotamiento que va más allá de lo físico.',
        'Es posible que el estrés esté afectando tu descanso.',
        'Parece que estás funcionando en piloto automático.',
        'Da la impresión de que tu cuerpo está en modo supervivencia.',
        'Se nota que llevas un peso que no te corresponde.',
        'Puede ser que estés dando más de lo que recibes.',
        'Parece que la rutina te está consumiendo.',
      ],
      suggestions: [
        '¿Qué tal si haces una pausa de 10 minutos?',
        'Respirar profundo puede darte un respiro mental.',
        'Escribir una lista de prioridades puede ayudar.',
        '¿Qué tal si delegas algo de lo que cargas?',
        'Un momento de silencio puede recargarte.',
        '¿Qué tal si sales a caminar un rato?',
        'Dormir temprano hoy podría ayudarte.',
        '¿Qué tal si dices "no" a algo hoy?',
        'Beber agua y comer algo puede darte energía.',
        'Escuchar música relajante puede calmar la mente.',
        'Meditar 5 minutos puede cambiar tu perspectiva.',
      ],
      questions: [
        '¿Qué es lo que más te está agobiando?',
        '¿Hay algo que puedas soltar por ahora?',
        '¿Desde cuándo te sientes así?',
        '¿Qué necesitas en este momento?',
        '¿Qué haría un amigo en tu lugar?',
        '¿Hay algo que estés evitando?',
        '¿Qué te gustaría cambiar de tu rutina?',
        '¿Cuándo fue la última vez que descansaste de verdad?',
        '¿Qué necesitas para recargar energías?',
        '¿Qué sería diferente si pudieras pausar todo?',
      ],
    ),
    'frustracion': _MessageBank(
      greetings: [
        'Veo que algo te está frustrando.',
        'Parece que no han sido las cosas como esperabas.',
        'Gracias por expresar lo que sientes.',
        'Se nota que hay algo que te está bloqueando.',
        'No es fácil cuando las cosas no salen como quieres.',
        'Tu frustración es comprensible.',
        'Estoy aquí para leerte.',
        'Me alegra que estés sacando lo que sientes.',
        'Tu diario es un buen lugar para esto.',
        'Parece que hoy ha sido frustrante.',
      ],
      validations: [
        'Tu frustración es una respuesta válida.',
        'No estás exagerando por sentirte así.',
        'Es humano frustrarse cuando las cosas no fluyen.',
        'No tienes que tener paciencia infinita.',
        'Tu enojo tiene razón de ser.',
        'No es fácil sentirse bloqueado.',
        'Está bien admitir que algo te está afectando.',
        'No necesitas justificar tu frustración.',
        'Tu sentimiento es real y tiene sentido.',
        'No estás mal por sentirte frustrado.',
      ],
      interpretations: [
        'Parece que algo te está impidiendo avanzar.',
        'Da la impresión de que hay un obstáculo que te detiene.',
        'Puede ser que las expectativas no estén coincidiendo con la realidad.',
        'Se percibe una sensación de estar atascado.',
        'Es posible que estés luchando contra algo que no controlas.',
        'Parece que tu esfuerzo no está dando los resultados esperados.',
        'Da la impresión de que necesitas un cambio de estrategia.',
        'Se nota que hay una tensión entre lo que quieres y lo que puedes.',
        'Puede ser que estés cargando con algo que no te corresponde.',
        'Parece que la situación te está generando impotencia.',
      ],
      suggestions: [
        '¿Qué tal si cambias de enfoque por un momento?',
        'Escribir qué es exactamente lo que te frustra puede aclarar.',
        'Respirar y soltar la tensión puede ayudar.',
        '¿Qué tal si divides el problema en partes?',
        'Una caminata puede darte nueva perspectiva.',
        '¿Qué tal si pides una segunda opinión?',
        'A veces descansar y volver con ojos frescos ayuda.',
        '¿Qué tal si aceptas que no puedes controlar todo?',
        'Hablar con alguien puede darte otro punto de vista.',
        '¿Qué tal si celebras los pequeños avances?',
      ],
      questions: [
        '¿Qué es exactamente lo que te está frustrando?',
        '¿Está bajo tu control o no?',
        '¿Qué harías si no tuvieras miedo de fallar?',
        '¿Qué has intentado hasta ahora?',
        '¿Hay algo que puedas hacer diferente?',
        '¿Qué le dirías a alguien en tu misma situación?',
        '¿Qué necesitas para sentir que avanzas?',
        '¿Hay algo que estés exigiéndote de más?',
        '¿Qué sería un pequeño paso adelante?',
        '¿Cuándo fue la última vez que algo te salió bien?',
      ],
    ),
    'culpa': _MessageBank(
      greetings: [
        'Veo que te estás juzgando con dureza.',
        'Parece que cargas con algo pesado.',
        'Gracias por ser honesto contigo mismo.',
        'No es fácil admitir lo que sientes.',
        'Me importa lo que estás viviendo.',
        'Tu diario es un lugar seguro para esto.',
        'Estoy aquí para leerte sin juzgarte.',
        'Se nota que hay algo que te pesa.',
        'Hablar de culpa requiere valentía.',
        'Gracias por confiarme esto.',
      ],
      validations: [
        'Cometer errores es humano.',
        'No definido por tus errores.',
        'Tu culpa no significa que seas mala persona.',
        'Todos nos equivocamos, es parte de vivir.',
        'No tienes que ser perfecto.',
        'El arrepentimiento muestra que te importa.',
        'No estás solo en sentirte así.',
        'Tu intención nunca fue hacer daño.',
        'Mereces perdón, especialmente el tuyo.',
        'No necesitas castigarte para aprender.',
      ],
      interpretations: [
        'Parece que estás lidiando con una sensación de arrepentimiento.',
        'Da la impresión de que te estás culpando más de lo necesario.',
        'Puede ser que estés reviviendo un error una y otra vez.',
        'Se percibe un deseo de haber hecho las cosas diferente.',
        'Es posible que la culpa te esté impidiendo avanzar.',
        'Parece que hay una差距 entre lo que hiciste y lo que querías hacer.',
        'Da la impresión de que necesitas perdonarte.',
        'Se nota que te importa mucho haber actuado bien.',
        'Puede ser que estás siendo más duro contigo del necesario.',
        'Parece que la culpa te está atrapando en el pasado.',
      ],
      suggestions: [
        'Escribir sobre qué sientes puede aliviar la carga.',
        '¿Qué le dirías a un amigo que se sintiera igual?',
        'Respirar y soltar puede ayudar.',
        '¿Qué tal si escribes una carta de perdón para ti?',
        'Meditar puede ayudarte a encontrar paz.',
        'Hablar con alguien puede darte perspectiva.',
        '¿Qué tal si aceptas que ya hiciste lo que pudiste?',
        'Un paseo puede ayudar a aclarar la mente.',
        '¿Qué tal si haces algo bueno por alguien hoy?',
        'Recordar tus aciertos puede equilibrar la balanza.',
      ],
      questions: [
        '¿Qué es lo que más te está pesando?',
        '¿Te estás castigando más de lo necesario?',
        '¿Qué le dirías a alguien en tu lugar?',
        '¿Hay algo que puedas hacer para reparar?',
        '¿Qué aprendiste de esto?',
        '¿Cuándo fue la última vez que te perdonaste?',
        '¿Qué necesitas para soltar esto?',
        '¿Qué sería diferente si pudieras volver atrás?',
        '¿Estás sendo justo contigo mismo?',
        '¿Qué necesitas para sentir paz?',
      ],
    ),
    'miedo': _MessageBank(
      greetings: [
        'Veo que algo te está generando temor.',
        'Parece que hay una preocupación profunda.',
        'Gracias por ser valiente y escribir esto.',
        'No es fácil enfrentar lo que nos da miedo.',
        'Tu miedo es comprensible.',
        'Estoy aquí para leerte.',
        'Me alegra que estés expresando esto.',
        'Tu diario es un lugar seguro.',
        'Se nota que algo te está inquietando.',
        'Hablar del miedo es el primer paso para enfrentarlo.',
      ],
      validations: [
        'Sentir miedo es natural y humano.',
        'No estás exagerando por sentirte así.',
        'Tu miedo tiene una razón de ser.',
        'Es válido sentirse asustado.',
        'No tienes que ser valiente todo el tiempo.',
        'Tu cuerpo se está protegiendo, es una respuesta natural.',
        'No es debilidad admitir que tienes miedo.',
        'Tu miedo merece ser escuchado.',
        'No necesitas justificar lo que sientes.',
        'Sentir miedo no significa que algo malo vaya a pasar.',
      ],
      interpretations: [
        'Parece que hay una amenaza percibida que te está afectando.',
        'Da la impresión de que tu mente está anticipando peligro.',
        'Puede ser que estés enfrentando algo desconocido.',
        'Se percibe una necesidad de seguridad.',
        'Es posible que el miedo te esté paralizando.',
        'Parece que necesitas sentirte a salvo.',
        'Da la impresión de que hay una incertidumbre que te agobia.',
        'Se nota que tu instinto de protección está activo.',
        'Puede ser que estés anticipando un escenario negativo.',
        'Parece que la situación te está fuera de control.',
      ],
      suggestions: [
        'Respirar profundo puede calmar tu sistema nervioso.',
        'Poner los pies en el suelo puede anclarte.',
        '¿Qué tal si identificas exactamente qué te da miedo?',
        'Hablar con alguien de confianza puede aliviar.',
        '¿Qué tal si te enfocas en lo que sí puedes controlar?',
        'Un abrazo largo puede darte seguridad.',
        'Escribir tu miedo puede hacer que se sienta menos poderoso.',
        '¿Qué tal si te recuerdas de veces que superaste miedos?',
        'Escuchar algo calmante puede relajarte.',
        '¿Qué tal si te das permiso para sentir miedo?',
      ],
      questions: [
        '¿Qué es lo que más te está asustando?',
        '¿Desde cuándo sientes este miedo?',
        '¿Qué harías si no tuvieras miedo?',
        '¿Hay algo que puedas hacer para sentirte más seguro?',
        '¿Qué necesitas para enfrentar esto?',
        '¿Qué le dirías a alguien que se sintiera igual?',
        '¿Qué sería lo peor que podría pasar?',
        '¿Qué te ha ayudado antes con el miedo?',
        '¿Hay algo que estés evitando por miedo?',
        '¿Qué necesitas para sentirte a salvo?',
      ],
    ),
    'vergüenza': _MessageBank(
      greetings: [
        'Veo que te sientes expuesto.',
        'Parece que algo te hizo sentir mal contigo mismo.',
        'Gracias por ser honesto.',
        'No es fácil hablar de esto.',
        'Tu valentía de escribir esto es notable.',
        'Estoy aquí sin juzgarte.',
        'Tu diario es un lugar seguro.',
        'Me importa lo que sientes.',
        'Se nota que hay algo que te avergüenza.',
        'Hablar de vergüenza requiere mucho valor.',
      ],
      validations: [
        'Todos sentimos vergüenza a veces.',
        'No estás solo en esto.',
        'Tu vergüenza no te define.',
        'Es humano equivocarse.',
        'No necesitas ser perfecto.',
        'Mereces compasión, especialmente la tuya.',
        'No estás tan mal como crees.',
        'Tu error no te hace una mala persona.',
        'La vergüenza es una emoción humana.',
        'No tienes que esconder lo que sientes.',
      ],
      interpretations: [
        'Parece que hay algo que te hizo sentir expuesto.',
        'Da la impresión de que te estás juzgando con dureza.',
        'Puede ser que sientas que no达到了 las expectativas.',
        'Se percibe una necesidad de aceptación.',
        'Es posible que te sientas vulnerable.',
        'Parece que algo te hizo sentir diferente.',
        'Da la impresión de que necesitas ser aceptado.',
        'Se nota que te importa mucho la opinión de otros.',
        'Puede ser que sientas que no encajas.',
        'Parece que algo te hizo sentir mal contigo mismo.',
      ],
      suggestions: [
        '¿Qué tal si hablas con alguien de confianza?',
        'Escribir sobre lo que sientes puede ayudar.',
        'Recuerda que todos cometemos errores.',
        '¿Qué tal si te tratas como tratarías a un amigo?',
        'Un momento de autocuidado puede ayudar.',
        '¿Qué tal si aceptas que eres humano?',
        'Hablar de vergüenza la hace menos poderosa.',
        '¿Qué tal si recuerdas tus cualidades?',
        'Meditar puede ayudar a encontrar paz.',
        '¿Qué tal si te das un abrazo?',
      ],
      questions: [
        '¿Qué es lo que más te avergüenza?',
        '¿Te estás juzgando más de lo necesario?',
        '¿Qué le dirías a alguien en tu lugar?',
        '¿Qué necesitas para sentirte mejor?',
        '¿Hay algo que puedas hacer para reparar?',
        '¿Qué aprendiste de esto?',
        '¿Cuándo fue la última vez que te sentiste orgulloso?',
        '¿Qué sería diferente si pudieras empezar de nuevo?',
        '¿Qué necesitas para sentirte aceptado?',
        '¿Qué cambiaría si pudieras verlo desde otro ángulo?',
      ],
    ),
    'alegria': _MessageBank(
      greetings: [
        '¡Qué bueno ver que algo te hizo sonreír!',
        'Me alegra que estés pasando un buen momento.',
        'Tu alegría se siente en tus palabras.',
        'Gracias por compartir algo positivo.',
        'Qué lindo que tengas algo que te haga sentir bien.',
        'Tu energía positiva se nota.',
        'Esto es genial de leer.',
        'Me alegra que algo te haya hecho feliz.',
        'Tu alegría es contagiosa.',
        'Qué bueno que estés disfrutando.',
      ],
      validations: [
        'Mereces sentirte bien.',
        'Tu alegría es tan válida como cualquier otra emoción.',
        'No tienes que justificar por qué estás feliz.',
        'Disfruta este momento.',
        'Tu felicidad es importante.',
        'Está bien celebrar los buenos momentos.',
        'No minimices lo que sientes.',
        'Tu alegría tiene derecho a existir.',
        'Permítete disfrutar sin culpa.',
        'Mereces estas cosas buenas.',
      ],
      interpretations: [
        'Parece que algo especial está ocurriendo.',
        'Da la impresión de que algo te hizo sentir vivo.',
        'Puede ser que estés experimentando una conexión profunda.',
        'Se percibe una sensación de plenitud.',
        'Es posible que algo haya cambiado positivamente.',
        'Parece que estás en sintonía con lo que importa.',
        'Da la impresión de que algo te hizo crecer.',
        'Se nota que algo te hizo sentir agradecido.',
        'Puede ser que estés disfrutando del momento.',
        'Parece que algo te hizo sentir en paz.',
      ],
      suggestions: [
        '¿Qué tal si escribes sobre qué te hizo sentir así?',
        'Compartir esta alegría con alguien puede multiplicarla.',
        '¿Qué tal si guardas este momento en tu memoria?',
        'Celebrar este momento es importante.',
        '¿Qué tal si repites algo de lo que te hizo sentir bien?',
        'Recordar esto en días difíciles puede ayudar.',
        '¿Qué tal si agradeces por esto?',
        'Disfrutar del momento sin prisa puede intensificarlo.',
        '¿Qué tal si haces algo más de lo que te gusta?',
        'Compartir tu alegría puede inspirar a otros.',
      ],
      questions: [
        '¿Qué te hizo sentir así?',
        '¿Cómo puedes replicar esta sensación?',
        '¿Qué aprendiste de esta experiencia?',
        '¿Qué te gustaría recordar de este momento?',
        '¿Cómo puedes compartir esta alegría?',
        '¿Qué significa esto para ti?',
        '¿Qué harás para mantener esta energía?',
        '¿Qué otro momento positivo recuerdas?',
        '¿Qué cambiaría si pudieras congelar este momento?',
        '¿Qué necesitas para seguir sintiéndote así?',
      ],
    ),
    'esperanza': _MessageBank(
      greetings: [
        'Veo que algo te está dando fuerzas.',
        'Parece que hay luz en tu horizonte.',
        'Me alegra que tengas esperanza.',
        'Tu optimismo se nota.',
        'Gracias por compartir esto.',
        'Es inspirador ver que miras hacia adelante.',
        'Tu esperanza es valiosa.',
        'Qué bueno que tengas algo que te motive.',
        'Se nota que algo te está impulsando.',
        'Tu energía positiva es notable.',
      ],
      validations: [
        'La esperanza es una fuerza poderosa.',
        'Tu optimismo es válido.',
        'No estás soñando demasiado.',
        'Mereces creer en algo mejor.',
        'Tu esperanza tiene sentido.',
        'No es ingenuo ser optimista.',
        'Tu fe en el futuro es importante.',
        'Está bien creer que las cosas mejorarán.',
        'Tu esperanza puede hacer la diferencia.',
        'No tienes que tener todas las respuestas.',
      ],
      interpretations: [
        'Parece que algo te está impulsando hacia adelante.',
        'Da la impresión de que estás viendo posibilidades.',
        'Puede ser que algo haya cambiado en tu perspectiva.',
        'Se percibe una sensación de apertura.',
        'Es posible que estés listo para algo nuevo.',
        'Parece que tu mirada está puesta en el futuro.',
        'Da la impresión de que algo te está motivando.',
        'Se nota que hay un deseo de crecimiento.',
        'Puede ser que estés en un punto de inflexión.',
        'Parece que algo te está dando dirección.',
      ],
      suggestions: [
        '¿Qué tal si escribes tus metas?',
        'Compartir tu esperanza puede fortalecerla.',
        '¿Qué tal si das un pequeño paso hoy?',
        'Recordar tu progreso puede motivarte.',
        '¿Qué tal si te rodeas de personas positivas?',
        'Visualizar tu futuro puede hacerlo más real.',
        '¿Qué tal si celebras cada pequeño avance?',
        'Escribir una carta a tu futuro yo puede ser útil.',
        '¿Qué tal si empiezas algo nuevo?',
        'Tu esperanza puede inspirar a otros.',
      ],
      questions: [
        '¿Qué te está dando esta esperanza?',
        '¿Qué te gustaría lograr?',
        '¿Qué pequeño paso puedes dar hoy?',
        '¿Qué necesitas para seguir adelante?',
        '¿Qué te motivó a sentirte así?',
        '¿Cómo puedes mantener esta energía?',
        '¿Qué le dirías a alguien que ha perdido la esperanza?',
        '¿Qué es lo mejor que podría pasar?',
        '¿Qué necesitas para creer más en ti?',
        '¿Cómo te sientes respecto al futuro?',
      ],
    ),
    'orgullo': _MessageBank(
      greetings: [
        '¡Qué bueno que te sientas orgulloso!',
        'Se nota que lograste algo importante.',
        'Tu orgullo es bien ganado.',
        'Me alegra ver que te valoras.',
        'Qué inspirador leer esto.',
        'Tu esfuerzo dio frutos.',
        'Esto es genial.',
        'Tu dedicación se nota.',
        'Qué lindo que reconozcas tu logro.',
        'Mereces este momento.',
      ],
      validations: [
        'Tu orgullo es completamente válido.',
        'Mereces celebrar esto.',
        'No estás exagerando, es un logro real.',
        'Tu esfuerzo fue real y significativo.',
        'Está bien sentirse bien contigo mismo.',
        'No minimices lo que lograste.',
        'Tu trabajo duro dio resultados.',
        'Mereces reconocimiento.',
        'Tu orgullo inspira.',
        'Celebra, te lo mereces.',
      ],
      interpretations: [
        'Parece que estás experimentando una sensación de logro.',
        'Da la impresión de que tu esfuerzo está siendo recompensado.',
        'Puede ser que estés reconociendo tu propio crecimiento.',
        'Se percibe una conexión con tu valor personal.',
        'Es posible que estés viendo el fruto de tu dedicación.',
        'Parece que algo te hizo sentir capaz.',
        'Da la impresión de que superaste un desafío.',
        'Se nota que hay una confianza creciente.',
        'Puede ser que estés descubriendo tu potencial.',
        'Parece que estás creciendo como persona.',
      ],
      suggestions: [
        '¿Qué tal si escribes sobre qué lograste?',
        'Compartir tu logro puede inspirar a otros.',
        '¿Qué tal si celebras de alguna forma?',
        'Recordar este momento en días difíciles puede ayudar.',
        '¿Qué tal si estableces una nueva meta?',
        'Tu ejemplo puede motivar a otros.',
        '¿Qué tal si te das las gracias por tu esfuerzo?',
        'Guarda este recuerdo, lo necesitarás.',
        '¿Qué tal si ayudas a alguien a lograr algo similar?',
        'Tu crecimiento es inspirador.',
      ],
      questions: [
        '¿Qué lograste exactamente?',
        '¿Qué te costó más?',
        '¿Qué aprendiste en el camino?',
        '¿Qué te gustaría lograr ahora?',
        '¿Cómo te sientes respecto a ti mismo?',
        '¿Qué le dirías a alguien que está empezando?',
        '¿Qué fue lo más difícil?',
        '¿Qué te mantuvo perseverando?',
        '¿Qué significó esto para ti?',
        '¿Qué sigue después de esto?',
      ],
    ),
    'soledad': _MessageBank(
      greetings: [
        'Veo que te sientes solo.',
        'Parece que la soledad se ha sentido fuerte.',
        'Gracias por escribir esto.',
        'No es fácil sentirse solo.',
        'Estoy aquí para leerte.',
        'Tu diario es un buen lugar para estar acompañado.',
        'Me importa lo que sientes.',
        'No estás tan solo como crees.',
        'Gracias por confiarme esto.',
        'Tu voz importa.',
      ],
      validations: [
        'Sentir soledad es humano.',
        'No estás exagerando.',
        'Tu soledad es real y válida.',
        'No necesitas tener gente alrededor para ser valioso.',
        'Estar solo no significa estar vacío.',
        'Tu presencia importa.',
        'No estás roto por sentirte solo.',
        'La soledad no define tu valor.',
        'Mereces conexión.',
        'No es debilidad sentirse solo.',
      ],
      interpretations: [
        'Parece que estás echando de menos la compañía.',
        'Da la impresión de que necesitas conexión humana.',
        'Puede ser que sientas que no te entienden.',
        'Se percibe una distancia con otros.',
        'Es posible que eches de menos algo específico.',
        'Parece que algo te está desconectando.',
        'Da la impresión de que necesitas ser visto.',
        'Se nota que extrañas algo o alguien.',
        'Puede ser que sientas que no encajas.',
        'Parece que necesitas pertenecer.',
      ],
      suggestions: [
        '¿Qué tal si escribes a alguien que extrañas?',
        'Hablar con alguien puede aliviar la soledad.',
        '¿Qué tal si buscas una actividad grupal?',
        'Escribir sobre lo que sientes puede ayudar.',
        '¿Qué tal si te conectas con alguien hoy?',
        'Recordar momentos buenos puede ayudar.',
        '¿Qué tal si haces algo por alguien?',
        'Un paseo puede hacer que te sientas menos solo.',
        '¿Qué tal si te unes a algo nuevo?',
        'La soledad es temporal, recuerda eso.',
      ],
      questions: [
        '¿Qué es lo que más extrañas?',
        '¿Desde cuándo te sientes así?',
        '¿Qué te gustaría que hiciera alguien por ti?',
        '¿Hay alguien a quien puedas escribir?',
        '¿Qué necesitas para sentirte acompañado?',
        '¿Qué te ayudó antes con la soledad?',
        '¿Qué harías si tuvieras compañía?',
        '¿Qué te impide buscar conexión?',
        '¿Qué sería diferente si no estuvieras solo?',
        '¿Qué necesitas para sentirte conectado?',
      ],
    ),
    'vacio': _MessageBank(
      greetings: [
        'Parece que algo se siente vacío.',
        'Gracias por escribir esto.',
        'Veo que no estás sintiendo mucho.',
        'No es fácil sentirse así.',
        'Estoy aquí para leerte.',
        'Tu diario es un buen lugar para expresar esto.',
        'Me importa lo que sientes.',
        'Gracias por ser honesto.',
        'No estás solo en esto.',
        'Tu voz importa.',
      ],
      validations: [
        'Sentir vacío es una experiencia válida.',
        'No estás roto por sentirte así.',
        'No tienes que sentir todo todo el tiempo.',
        'Tu vacío merece atención.',
        'No es debilidad sentirse vacío.',
        'Tu experiencia es real.',
        'No necesitas justificar lo que sientes.',
        'Estar vacío no significa estar roto.',
        'Tu sentimiento tiene sentido.',
        'Está bien no sentir nada a veces.',
      ],
      interpretations: [
        'Parece que algo se ha apagado por dentro.',
        'Da la impresión de que necesitas reconectar.',
        'Puede ser que estés en un período de transición.',
        'Se percibe una desconexión emocional.',
        'Es posible que necesites descubrir qué te importa.',
        'Parece que algo te está consumiendo.',
        'Da la impresión de que necesitas un reinicio.',
        'Se nota que algo falta.',
        'Puede ser que estés en piloto automático.',
        'Parece que necesitas volver a sentir.',
      ],
      suggestions: [
        '¿Qué tal si intentas algo nuevo?',
        'Escribir puede ayudar a reconectar.',
        '¿Qué tal si haces algo que antes te gustaba?',
        'Un cambio de rutina puede ayudar.',
        '¿Qué tal si buscas algo que te emocione?',
        'Hablar con alguien puede abrir puertas.',
        '¿Qué tal si exploras algo diferente?',
        'La naturaleza puede ayudar a reconectar.',
        '¿Qué tal si te das permiso para sentir?',
        'Un momento de silencio puede revelar algo.',
      ],
      questions: [
        '¿Qué sientes que falta?',
        '¿Desde cuándo te sientes así?',
        '¿Qué te emocionaba antes?',
        '¿Qué necesitas para sentir?',
        '¿Qué cambiarías de tu vida?',
        '¿Qué te gustaría sentir?',
        '¿Hay algo que te dé aunque sea un poco de emoción?',
        '¿Qué harías si pudieras sentir algo?',
        '¿Qué necesitas para reconectar?',
        '¿Qué te gustaría descubrir de ti?',
      ],
    ),
    'burnout': _MessageBank(
      greetings: [
        'Veo que estás agotado.',
        'Parece que llevas mucho peso.',
        'Gracias por escribir esto.',
        'No es fácil admitir que no puedes más.',
        'Estoy aquí para leerte.',
        'Tu esfuerzo se reconoce.',
        'Me importa lo que estás viviendo.',
        'No estás exagerando.',
        'Tu cansancio es real.',
        'Gracias por ser honesto.',
      ],
      validations: [
        'Tu agotamiento es válido.',
        'No estás fallando, estás sobreviviendo.',
        'Es humano llegar al límite.',
        'No tienes que ser invencible.',
        'Tu cuerpo te está pidiendo descanso.',
        'No es debilidad rendirse.',
        'Mereces descansar.',
        'No tienes que dar más de lo que puedes.',
        'Tu límite es real.',
        'Está bien decir "no puedo más".',
      ],
      interpretations: [
        'Parece que estás en un punto de quiebre.',
        'Da la impresión de que has estado dando sin recibir.',
        'Puede ser que el desgaste acumulado te esté alcanzando.',
        'Se percibe una pérdida de energía vital.',
        'Es posible que necesites un cambio radical.',
        'Parece que algo te está drenando.',
        'Da la impresión de que necesitas reinventarte.',
        'Se nota que has estado en supervivencia.',
        'Puede ser que estés en un período de agotamiento.',
        'Parece que necesitas un reinicio.',
      ],
      suggestions: [
        '¿Qué tal si tomas un día libre?',
        'Dormir puede ser lo más importante ahora.',
        '¿Qué tal si delegas algo?',
        'Una pausa prolongada puede ser necesaria.',
        '¿Qué tal si reduces tus compromisos?',
        'Tu salud es prioridad.',
        '¿Qué tal si pides ayuda?',
        'Un cambio de aire puede recargarte.',
        '¿Qué tal si desconectas un tiempo?',
        'Tu cuerpo necesita recuperarse.',
      ],
      questions: [
        '¿Qué es lo que más te está drenando?',
        '¿Desde cuándo te sientes así?',
        '¿Qué necesitas para recargar?',
        '¿Hay algo que puedas soltar?',
        '¿Qué te gustaría cambiar?',
        '¿Cuándo fue la última vez que descansaste?',
        '¿Qué necesitas para recuperarte?',
        '¿Qué harías si pudieras parar todo?',
        '¿Qué te impide descansar?',
        '¿Qué sería diferente si priorizaras tu salud?',
      ],
    ),
    'nostalgia': _MessageBank(
      greetings: [
        'Veo que estás recordando.',
        'Parece que algo del pasado te está llamando.',
        'Gracias por compartir esto.',
        'No es fácil enfrentar recuerdos.',
        'Estoy aquí para leerte.',
        'Tu diario es un buen lugar para esto.',
        'Me importa lo que sientes.',
        'Los recuerdos pueden ser complicados.',
        'Gracias por ser honesto.',
        'Tu nostalgia tiene sentido.',
      ],
      validations: [
        'Extrañar es humano.',
        'Tus recuerdos son valiosos.',
        'No es débil sentir nostalgia.',
        'Tu pasado forma parte de ti.',
        'Extrañar muestra que te importó.',
        'No tienes que olvidar para avanzar.',
        'Tu nostalgia es comprensible.',
        'Los recuerdos son parte de quien eres.',
        'Está bien mirar hacia atrás.',
        'Tu memoria tiene valor.',
      ],
      interpretations: [
        'Parece que algo del pasado te está marcando.',
        'Da la impresión de que extrañas algo específico.',
        'Puede ser que estés comparando épocas.',
        'Se percibe una conexión con momentos anteriores.',
        'Es posible que eches de menos algo que tenías.',
        'Parece que algo te hizo recordar.',
        'Da la impresión de que necesitas cerrar algo.',
        'Se nota que el pasado tiene peso.',
        'Puede ser que estés en un punto de reflexión.',
        'Parece que algo te hizo mirar atrás.',
      ],
      suggestions: [
        '¿Qué tal si escribes sobre qué recuerdas?',
        'Hablar de tu pasado puede ser sanador.',
        '¿Qué tal si honras esos recuerdos?',
        'Un álbum de fotos puede ayudar.',
        '¿Qué tal si escribes una carta?',
        'Los recuerdos pueden ser una guía.',
        '¿Qué tal si extraes lo bueno del pasado?',
        'Un paseo por lugares significativos puede ayudar.',
        '¿Qué tal si creas nuevos recuerdos?',
        'Tu pasado puede enseñarte algo.',
      ],
      questions: [
        '¿Qué extrañas más?',
        '¿Qué momento estás recordando?',
        '¿Qué aprendiste de esa época?',
        '¿Qué te gustaría revivir?',
        '¿Qué cambiarías si pudieras?',
        '¿Qué significó eso para ti?',
        '¿Cómo te sientes ahora vs entonces?',
        '¿Qué necesitas para encontrar paz con el pasado?',
        '¿Qué te gustaría preservar?',
        '¿Qué sigue después de mirar atrás?',
      ],
    ),
    'calma': _MessageBank(
      greetings: [
        'Parece que estás en un buen lugar.',
        'Tu calma se nota.',
        'Qué bueno que te sientas en paz.',
        'Gracias por compartir esto.',
        'Tu tranquilidad es inspiradora.',
        'Me alegra que estés bien.',
        'Tu energía es serena.',
        'Qué lindo leerte.',
        'Tu paz interior se percibe.',
        'Esto es reconfortante.',
      ],
      validations: [
        'Mereces esta calma.',
        'Tu paz es importante.',
        'No tienes que estar agitado para ser productivo.',
        'La calma es una fortaleza.',
        'Tu serenidad tiene valor.',
        'Disfruta este momento.',
        'Mereces sentirte en paz.',
        'Tu tranquilidad es un logro.',
        'No tienes que justificar tu calma.',
        'Esta paz es tuya, disfrútala.',
      ],
      interpretations: [
        'Parece que has encontrado un equilibrio.',
        'Da la impresión de que algo te está dando paz.',
        'Puede ser que estés en un momento de clarity.',
        'Se percibe una armonía interior.',
        'Es posible que estés en sintonía contigo mismo.',
        'Parece que algo te hizo encontrar calma.',
        'Da la impresión de que has soltado tensión.',
        'Se nota que hay una paz genuina.',
        'Puede ser que estés en un buen momento.',
        'Parece que algo te está nutriendo.',
      ],
      suggestions: [
        '¿Qué tal si mantienes esta sensación?',
        'Escribir sobre qué te da calma puede ayudar.',
        '¿Qué tal si compartes tu paz con otros?',
        'Recordar este momento puede ser útil.',
        '¿Qué tal si repites lo que te hizo sentir así?',
        'Tu calma puede inspirar a otros.',
        '¿Qué tal si meditas para profundizar?',
        'Disfrutar del momento sin prisa es clave.',
        '¿Qué tal si ayudas a alguien a encontrar calma?',
        'Tu paz interior es un tesoro.',
      ],
      questions: [
        '¿Qué te está dando esta calma?',
        '¿Cómo puedes mantener esta sensación?',
        '¿Qué aprendiste de este momento?',
        '¿Qué necesitas para seguir así?',
        '¿Cómo puedes compartir esta paz?',
        '¿Qué significa esta calma para ti?',
        '¿Qué harás para protegerla?',
        '¿Qué otro momento de calma recuerdas?',
        '¿Qué necesitas para profundizar?',
        '¿Cómo te sientes en este momento?',
      ],
    ),
    'desesperanza': _MessageBank(
      greetings: [
        'Veo que estás pasando por un momento muy difícil.',
        'Parece que todo se siente pesado.',
        'Gracias por escribir esto.',
        'No es fácil sentirse así.',
        'Estoy aquí para leerte.',
        'Tu diario es un lugar seguro.',
        'Me importa mucho lo que sientes.',
        'No estás solo en esto.',
        'Gracias por confiarme esto.',
        'Tu dolor es real.',
      ],
      validations: [
        'Sentir desesperanza es humano.',
        'No estás exagerando.',
        'Tu dolor es válido.',
        'No tienes que estar bien todo el tiempo.',
        'Tu sentimiento tiene sentido.',
        'No es debilidad sentirse así.',
        'Mereces ser escuchado.',
        'Tu sufrimiento es real.',
        'No necesitas justificar lo que sientes.',
        'Está bien no estar bien.',
      ],
      interpretations: [
        'Parece que algo te está haciendo sentir sin salida.',
        'Da la impresión de que necesitas ver luz.',
        'Puede ser que algo haya cambiado.',
        'Se percibe una pérdida de esperanza.',
        'Es posible que estés en un punto bajo.',
        'Parece que necesitas un cambio de perspectiva.',
        'Da la impresión de que algo te está consumiendo.',
        'Se nota que algo te está doliendo.',
        'Puede ser que algo te haya afectado profundamente.',
        'Parece que necesitas reconectar con algo.',
      ],
      suggestions: [
        'Hablar con alguien puede ayudar mucho.',
        'No tienes que cargar con esto solo.',
        '¿Qué tal si escribes más sobre qué sientes?',
        'Buscar ayuda profesional puede ser un paso.',
        'No tienes que resolver todo hoy.',
        'Hablar con alguien de confianza puede aliviar.',
        'No estás roto, estás herido.',
        'Tu vida tiene valor.',
        '¿Qué tal si pides ayuda?',
        'Hay personas que pueden escucharte.',
      ],
      questions: [
        '¿Qué es lo que más te está doliendo?',
        '¿Desde cuándo te sientes así?',
        '¿Qué necesitas en este momento?',
        '¿Hay alguien con quien puedas hablar?',
        '¿Qué te ayudó antes?',
        '¿Qué cambiarías si pudieras?',
        '¿Qué necesitas para sentir esperanza?',
        '¿Qué le dirías a alguien en tu lugar?',
        '¿Qué sería lo mejor que podría pasar?',
        '¿Qué necesitas para seguir adelante?',
      ],
    ),
    'incertidumbre': _MessageBank(
      greetings: [
        'Veo que hay muchas dudas.',
        'Parece que no sabes qué hacer.',
        'Gracias por escribir esto.',
        'No es fácil estar en la incertidumbre.',
        'Estoy aquí para leerte.',
        'Tu diario es un buen lugar para ordenar.',
        'Me importa lo que estás viviendo.',
        'La incertidumbre puede ser agotadora.',
        'Gracias por ser honesto.',
        'No estás solo en esto.',
      ],
      validations: [
        'No tener respuestas es humano.',
        'Está bien no saber.',
        'Tu confusión es válida.',
        'No tienes que tener todo claro.',
        'La incertidumbre es parte de la vida.',
        'No es debilidad dudar.',
        'Tu proceso tiene sentido.',
        'No necesitas todas las respuestas ahora.',
        'Está bien tomar tu tiempo.',
        'Tu duda es comprensible.',
      ],
      interpretations: [
        'Parece que algo te está generando dudas.',
        'Da la impresión de que estás en una encrucijada.',
        'Puede ser que algo haya cambiado.',
        'Se percibe una necesidad de dirección.',
        'Es posible que estés en un período de cambio.',
        'Parece que algo te está haciendo cuestionar.',
        'Da la impresión de que necesitas claridad.',
        'Se nota que algo te está inquietando.',
        'Puede ser que algo te esté desafiando.',
        'Parece que necesitas un punto de referencia.',
      ],
      suggestions: [
        'Escribir tus opciones puede aclarar.',
        'Hablar con alguien puede dar perspectiva.',
        '¿Qué tal si tomas una decisión pequeña?',
        'Un paseo puede ayudar a pensar.',
        '¿Qué tal si hablas con alguien que confíes?',
        'Dormir puede darte claridad.',
        '¿Qué tal si te das tiempo?',
        'Un cambio de escenario puede ayudar.',
        '¿Qué tal si evalúas tus prioridades?',
        'A veces la respuesta viene con el tiempo.',
      ],
      questions: [
        '¿Qué es lo que más te está confundiendo?',
        '¿Qué opciones tienes?',
        '¿Qué necesitas para decidir?',
        '¿Qué te gustaría que pasara?',
        '¿Qué te ayudaría a tener claridad?',
        '¿Qué harías si no tuvieras miedo?',
        '¿Qué es lo peor que podría pasar?',
        '¿Qué es lo mejor que podría pasar?',
        '¿Qué necesitas para sentirte seguro?',
        '¿Qué te dice tu instinto?',
      ],
    ),
    'enojo': _MessageBank(
      greetings: [
        'Veo que algo te está molestando.',
        'Parece que algo te hizo enojar.',
        'Gracias por expresar lo que sientes.',
        'Tu enojo es comprensible.',
        'Estoy aquí para leerte.',
        'Tu diario es un buen lugar para esto.',
        'Me importa lo que estás viviendo.',
        'No es fácil manejar el enojo.',
        'Gracias por ser honesto.',
        'Tu enojo tiene una razón.',
      ],
      validations: [
        'Sentir enojo es humano.',
        'No estás exagerando.',
        'Tu enojo es válido.',
        'No tienes que contener tu enojo.',
        'Tu enojo tiene sentido.',
        'Es humano enojarse.',
        'No es malo sentir enojo.',
        'Tu enojo merece ser escuchado.',
        'No necesitas justificar tu enojo.',
        'Tu enojo es una emoción válida.',
      ],
      interpretations: [
        'Parece que algo te está afectando profundamente.',
        'Da la impresión de que algo te hizo sentir injusto.',
        'Puede ser que algo haya cruzado un límite.',
        'Se percibe una sensación de injusticia.',
        'Es posible que algo te haya dolido.',
        'Parece que algo te está generando tensión.',
        'Da la impresión de que algo te está bloqueando.',
        'Se nota que algo te está afectando.',
        'Puede ser que algo te haya herido.',
        'Parece que necesitas expresar algo.',
      ],
      suggestions: [
        'Respirar profundo puede ayudar.',
        'Escribir tu enojo puede liberar.',
        '¿Qué tal si canalizas la energía?',
        'Una caminata puede darte perspectiva.',
        '¿Qué tal si identificas qué te enoja?',
        'Hablar con alguien puede ayudar.',
        '¿Qué tal si tomas una pausa?',
        'Ejercicio puede liberar la tensión.',
        '¿Qué tal si escribes sin filtro?',
        'Un momento de silencio puede calmar.',
      ],
      questions: [
        '¿Qué es lo que más te está enojando?',
        '¿Qué te hizo sentir así?',
        '¿Está bajo tu control?',
        '¿Qué necesitas para sentirte mejor?',
        '¿Qué harías si pudieras expresar tu enojo?',
        '¿Qué necesitas para soltar?',
        '¿Qué cambiarías si pudieras?',
        '¿Qué le dirías a alguien en tu lugar?',
        '¿Qué necesitas para sentir JUSTICIA?',
        '¿Qué te ayudaría a calmarte?',
      ],
    ),
    'motivacion': _MessageBank(
      greetings: [
        '¡Veo que estás motivado!',
        'Tu energía se nota.',
        'Qué bueno que tengas impulso.',
        'Gracias por compartir esto.',
        'Tu motivación es inspiradora.',
        'Me alegra ver que avanzas.',
        'Tu energía positiva se siente.',
        'Qué lindo leerte.',
        'Esto es genial.',
        'Mereces este impulso.',
      ],
      validations: [
        'Tu motivación es válida.',
        'Mereces avanzar.',
        'No estás soñando demasiado.',
        'Tu energía es un recurso.',
        'Mereces alcanzar tus metas.',
        'Tu motivación tiene sentido.',
        'Está bien sentirse motivado.',
        'Tu impulso es real.',
        'No necesitas justificar tu energía.',
        'Mereces sentirte así.',
      ],
      interpretations: [
        'Parece que algo te está impulsando.',
        'Da la impresión de que tienes un objetivo claro.',
        'Puede ser que algo haya cambiado.',
        'Se percibe una dirección.',
        'Es posible que estés listo para algo nuevo.',
        'Parece que algo te está motivando.',
        'Da la impresión de que tienes energía.',
        'Se nota que algo te está impulsando.',
        'Puede ser que algo te esté inspirando.',
        'Parece que estás en un buen momento.',
      ],
      suggestions: [
        '¿Qué tal si canalizas esta energía?',
        'Escribir tus metas puede ayudar.',
        '¿Qué tal si empiezas algo hoy?',
        'Un plan de acción puede darte dirección.',
        '¿Qué tal si compartes tu motivación?',
        'Tu energía puede inspirar a otros.',
        '¿Qué tal si celebras cada paso?',
        'Un pequeño avance es un avance.',
        '¿Qué tal si te desafías?',
        'Tu motivación puede ser contagiosa.',
      ],
      questions: [
        '¿Qué te está motivando?',
        '¿Qué quieres lograr?',
        '¿Qué paso puedes dar hoy?',
        '¿Qué necesitas para mantener la motivación?',
        '¿Qué te impulsa?',
        '¿Qué harás con esta energía?',
        '¿Qué meta quieres alcanzar?',
        '¿Qué necesitas para tener éxito?',
        '¿Cómo te sientes respecto a esto?',
        '¿Qué sigue?',
      ],
    ),
    'inspiracion': _MessageBank(
      greetings: [
        '¡Veo que algo te está inspirando!',
        'Tu creatividad se nota.',
        'Qué bueno que tengas ideas.',
        'Gracias por compartir esto.',
        'Tu inspiración es valiosa.',
        'Me alegra ver que creas.',
        'Tu energía creativa se siente.',
        'Qué lindo leerte.',
        'Esto es inspirador.',
        'Mereces este momento.',
      ],
      validations: [
        'Tu inspiración es válida.',
        'Mereces crear.',
        'No estás soñando demasiado.',
        'Tu creatividad tiene valor.',
        'Mereces expresarte.',
        'Tu inspiración tiene sentido.',
        'Está bien sentirse inspirado.',
        'Tu energía creativa es real.',
        'No necesitas justificar tu inspiración.',
        'Mereces sentirte así.',
      ],
      interpretations: [
        'Parece que algo te está inspirando.',
        'Da la impresión de que tienes ideas.',
        'Puede ser que algo haya despertado tu creatividad.',
        'Se percibe una chispa.',
        'Es posible que algo te haya estimulado.',
        'Parece que algo te está nutriendo.',
        'Da la impresión de que tienes ganas de crear.',
        'Se nota que algo te está inspirando.',
        'Puede ser que algo te haya emocionado.',
        'Parece que estás en un momento creativo.',
      ],
      suggestions: [
        '¿Qué tal si desarrollas una idea?',
        'Escribir puede ayudar a materializar.',
        '¿Qué tal si creas algo hoy?',
        'Un proyecto puede darte dirección.',
        '¿Qué tal si compartes tu inspiración?',
        'Tu creatividad puede inspirar a otros.',
        '¿Qué tal si exploras una nueva forma?',
        'Un cambio de escenario puede ayudar.',
        '¿Qué tal si experimentas?',
        'Tu inspiración puede ser valiosa.',
      ],
      questions: [
        '¿Qué te está inspirando?',
        '¿Qué quieres crear?',
        '¿Qué paso puedes dar hoy?',
        '¿Qué necesitas para mantener la inspiración?',
        '¿Qué te inspira?',
        '¿Qué harás con esta energía?',
        '¿Qué idea quieres desarrollar?',
        '¿Qué necesitas para crear?',
        '¿Cómo te sientes respecto a esto?',
        '¿Qué sigue?',
      ],
    ),
  };

  static EmotionalResponse generate(EmotionInterpretation interpretation) {
    if (interpretation.primaryEmotions.isEmpty) {
      return EmotionalResponse(
        greeting: 'Gracias por escribir.',
        validation: 'Está bien expresar lo que sientes.',
        interpretation: interpretation.summary,
        suggestion: '¿Qué tal si escribes un poco más sobre cómo te sientes?',
        reflectionQuestion: '¿Qué necesitas en este momento?',
        emergencyRisk: false,
      );
    }

    final primary = interpretation.primaryEmotions.first.emotion.id;
    final bank = _banks[primary] ?? _banks['tristeza']!;

    return EmotionalResponse(
      greeting: _pick(bank.greetings, interpretation),
      validation: _pick(bank.validations, interpretation),
      interpretation: interpretation.summary,
      suggestion: _pick(bank.suggestions, interpretation),
      reflectionQuestion: _pick(bank.questions, interpretation),
      emergencyRisk: false,
    );
  }

  static EmotionalResponse generateWithCrisis(
    EmotionInterpretation interpretation,
    CrisisResult crisis,
  ) {
    final base = generate(interpretation);

    if (crisis.highRisk) {
      return EmotionalResponse(
        greeting: 'Gracias por escribir. Sé que no es fácil.',
        validation: 'Lo que estás sintiendo es real y válido.',
        interpretation:
            'Parece que estás pasando por un momento muy difícil.',
        suggestion:
            'Hay personas que pueden ayudarte. Línea de la Vida: 800 911 2000. '
            'No estás solo.',
        reflectionQuestion: '¿Hay alguien con quien puedas hablar ahora?',
        emergencyRisk: true,
      );
    }

    return base;
  }

  static String _pick(List<String> messages, EmotionInterpretation interp) {
    final seed = interp.summary.hashCode +
        interp.primaryEmotions.length +
        DateTime.now().millisecondsSinceEpoch;
    final index = seed.abs() % messages.length;
    return messages[index];
  }

  static final List<String> _recentGreetings = [];
  static final List<String> _recentValidations = [];
  static const int _maxRecent = 8;

  static String _pickUnique(
    List<String> messages,
    List<String> recent,
    EmotionInterpretation interp,
  ) {
    final available = messages.where((m) => !recent.contains(m)).toList();
    final pool = available.isNotEmpty ? available : messages;
    final seed = interp.summary.hashCode +
        interp.primaryEmotions.length +
        DateTime.now().millisecondsSinceEpoch;
    final picked = pool[seed.abs() % pool.length];
    recent.add(picked);
    if (recent.length > _maxRecent) {
      recent.removeAt(0);
    }
    return picked;
  }

  static EmotionalResponse generateWithContext(ResponseContext context) {
    if (context.crisis.highRisk) {
      return generateWithCrisis(context.interpretation, context.crisis);
    }

    if (context.interpretation.primaryEmotions.isEmpty) {
      return EmotionalResponse(
        greeting: 'Gracias por escribir.',
        validation: 'Está bien expresar lo que sientes.',
        interpretation: context.interpretation.summary,
        suggestion:
            '¿Qué tal si escribes un poco más sobre cómo te sientes?',
        reflectionQuestion: '¿Qué necesitas en este momento?',
        emergencyRisk: false,
      );
    }

    final primary =
        context.interpretation.primaryEmotions.first.emotion.id;
    final bank = _banks[primary] ?? _banks['tristeza']!;

    final greeting = _pickUnique(
      bank.greetings,
      _recentGreetings,
      context.interpretation,
    );
    final validation = _pickUnique(
      bank.validations,
      _recentValidations,
      context.interpretation,
    );

    final parts = <String>[context.interpretation.summary];

    if (context.history.length >= 3) {
      final recentEmotions = <String>{};
      for (final a in context.history.takeLast(5)) {
        if (a.rankings.isNotEmpty) {
          recentEmotions.add(a.rankings.first.emotion.name);
        }
      }
      if (recentEmotions.length >= 2) {
        parts.add(
          'He notado un patrón en tus emociones recientes: '
          '${recentEmotions.join(", ")}.',
        );
      }
    }

    if (context.relatedMemory != null) {
      final m = context.relatedMemory!;
      final timePhrase = m.timesMentioned >= 3
          ? 'Volvemos a hablar de'
          : 'La última vez me contaste sobre';
      parts.add('$timePhrase "${m.value}". ¿Cómo ha ido desde entonces?');
    }

    if (context.conversationContext != null) {
      final cc = context.conversationContext!;
      if (cc.tendenciaEmocional == 'mejorando') {
        parts.add(
          'He visto que tus emociones han mejorado recientemente. '
          'Sigue así.',
        );
      } else if (cc.tendenciaEmocional == 'empeorando') {
        parts.add(
          'Parece que los últimos días han sido más intensos. '
          'Está bien pedir ayuda.',
        );
      }
      if (cc.temasRecurrentes.isNotEmpty) {
        parts.add(
          'Veo que "${cc.temasRecurrentes.first}" sigue presente. '
          '¿Qué ha pasado desde la última vez?',
        );
      }
    }

    final interpretation = parts.join(' ');

    final suggestion = _pickUnique(
      bank.suggestions,
      [],
      context.interpretation,
    );
    final question = _pickUnique(
      bank.questions,
      [],
      context.interpretation,
    );

    return EmotionalResponse(
      greeting: greeting,
      validation: validation,
      interpretation: interpretation,
      suggestion: suggestion,
      reflectionQuestion: question,
      emergencyRisk: false,
    );
  }
}

extension _ListLast<T> on List<T> {
  List<T> takeLast(int count) {
    if (length <= count) return this;
    return sublist(length - count);
  }
}
